# Generated by Django 2.2 on 2023-03-14 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 3, 14, 14, 23, 51, 303567, tzinfo=utc))),
            ],
        ),
    ]
